// Level 3 — Grammars & Parsing
LT.registerLevel({
  id: 3,
  title: 'Grammars & Parsing',
  whyItMatters: 'Parsing is what turns a flat list of tokens into a tree that captures structure. Every parser is some flavor of "match grammar rules to tokens".',
  glossary: ['parser', 'grammar', 'CFG', 'BNF', 'recursive descent', 'precedence', 'associativity', 'ambiguity', 'parse tree', 'lookahead'],
  learn:
    '<p>The parser is the second stage. It takes the token list from the lexer and produces a tree. The grammar tells it what shapes are allowed.</p>' +

    '<h4>Context-free grammars</h4>' +
    '<p>The grammars used for programming languages are <b>context-free</b>: each rule expands one nonterminal, and the expansion does not depend on what came before. We write them in <b>BNF</b> or a close variant. A typical arithmetic grammar:</p>' +
    '<div class="formula-box">' +
    'expr   ::= term (("+" | "-") term)*<br>' +
    'term   ::= factor (("*" | "/") factor)*<br>' +
    'factor ::= NUMBER | "(" expr ")"' +
    '</div>' +
    '<p>Three things to notice. First, multiplication is "below" addition — that is how the grammar encodes <b>precedence</b> (×/÷ bind tighter than +/−). Second, the loop <code class="inline">(... term)*</code> encodes left-to-right <b>associativity</b> for + and −. Third, parens give you a way to escape both rules.</p>' +

    '<h4>Recursive descent</h4>' +
    '<p><b>Recursive descent</b> is the most common hand-written parsing technique. The recipe is mechanical: write one function per grammar rule, and have it consume tokens that match that rule. Returning means "matched"; throwing means "syntax error".</p>' +
    '<div class="formula-box">' +
    'function expr() {<br>' +
    '&nbsp;&nbsp;var left = term();<br>' +
    '&nbsp;&nbsp;while (peek is "+" or "-") {<br>' +
    '&nbsp;&nbsp;&nbsp;&nbsp;var op = eat();<br>' +
    '&nbsp;&nbsp;&nbsp;&nbsp;var right = term();<br>' +
    '&nbsp;&nbsp;&nbsp;&nbsp;left = BinaryOp(op, left, right);<br>' +
    '&nbsp;&nbsp;}<br>' +
    '&nbsp;&nbsp;return left;<br>' +
    '}' +
    '</div>' +
    '<p><code class="inline">peek</code> looks at the next token without consuming it (this is called <b>lookahead</b>; one token is enough for most languages). <code class="inline">eat</code> consumes it. Each function calls into the next "tighter" rule (term calls factor, factor calls expr if it sees a paren).</p>' +

    '<h4>Why precedence is just nesting</h4>' +
    '<p>In <code class="inline">1 + 2 * 3</code>, the parser starts in <code class="inline">expr</code>, calls <code class="inline">term</code>, which reads <code class="inline">1</code> and returns. Back in <code class="inline">expr</code>, the parser sees <code class="inline">+</code>, eats it, and calls <code class="inline">term</code> again. <code class="inline">term</code> reads <code class="inline">2</code>, sees <code class="inline">*</code>, eats it, calls <code class="inline">factor</code>, gets <code class="inline">3</code>, builds <code class="inline">2*3</code>, returns that. Back in <code class="inline">expr</code>, the result is <code class="inline">1 + (2*3)</code>.</p>' +
    '<p>The shape of the tree comes straight from the call structure of the parser. That is the whole trick.</p>' +

    '<h4>Ambiguity</h4>' +
    '<p>A grammar is <b>ambiguous</b> if some input has more than one valid parse tree. The classic case is the <b>dangling else</b>:</p>' +
    '<div class="formula-box">' +
    'if (a) if (b) X else Y' +
    '</div>' +
    '<p>Does <code class="inline">else Y</code> attach to the inner <code class="inline">if (b)</code> or the outer <code class="inline">if (a)</code>? With a naïve grammar, both parses are legal. C, Java, and most others fix this by convention: <b>else</b> attaches to the <i>nearest</i> if. The grammar can be rewritten to enforce that, but it is uglier.</p>' +

    '<h4>Other parsing styles, briefly</h4>' +
    '<ul>' +
    '<li><b>LL(k)</b>: top-down, k tokens of lookahead. Recursive descent is hand-written LL(1) usually.</li>' +
    '<li><b>LR / LALR</b>: bottom-up. Generated by tools like Yacc/Bison. Handles a strict superset of LL grammars.</li>' +
    '<li><b>PEG</b>: "ordered choice" grammars — alternatives are tried in order. Avoids ambiguity by construction.</li>' +
    '<li><b>Pratt parsing</b>: a clean trick for handling precedence in expressions. Used in many real languages (Go, the V8 expression parser).</li>' +
    '</ul>',

  mountPlay: function (container) {
    container.innerHTML =
      '<p class="muted">Type an arithmetic expression. The parser builds the AST and shows it as an indented tree.</p>' +
      '<input type="text" id="lt-parse-in" style="width:100%;" value="1 + 2 * 3 - 4">' +
      '<div id="lt-parse-out" class="expr-tree" style="margin-top:10px;min-height:60px;"></div>';
    var inp = container.querySelector('#lt-parse-in');
    var out = container.querySelector('#lt-parse-out');
    function update() {
      try {
        var toks = LT.lib.lex.tokenize(inp.value);
        var ast = LT.lib.parse.parse(toks);
        out.textContent = LT.lib.parse.astTree(ast);
        out.style.color = '';
      } catch (e) {
        out.textContent = e.message;
        out.style.color = 'var(--bad)';
      }
    }
    inp.addEventListener('input', update);
    update();
  },

  puzzles: [
    {
      difficulty: 'easy',
      prompt: '<p>Using the grammar from the lesson:</p>' +
              '<div class="formula-box">' +
              'expr ::= term (("+" | "-") term)*<br>' +
              'term ::= factor (("*" | "/") factor)*<br>' +
              'factor ::= NUMBER | "(" expr ")"' +
              '</div>' +
              '<p>What does <code class="inline">2 + 3 * 4</code> evaluate to?</p>',
      mountInput: function (container) {
        var inp = document.createElement('input');
        inp.type = 'number';
        container.appendChild(inp);
        return function () { return parseFloat(inp.value); };
      },
      check: function (v) {
        if (v === 14) return { correct: true, feedback: 'Right. The grammar gives × higher precedence by putting term "below" expr, so 3*4 binds first.' };
        if (v === 20) return { correct: false, feedback: 'That would be (2+3)*4. Look at the grammar: which operator binds tighter?' };
        return { correct: false, feedback: 'Compute 3*4 first (because term sits below expr in the grammar — that is precedence), then add 2.' };
      },
      hints: [
        'In the grammar, term is "below" expr. That means it binds tighter.',
        'So 3 * 4 happens before 2 + (anything).',
        'Answer = 2 + (3*4) = 2 + 12.'
      ]
    },
    {
      difficulty: 'medium',
      prompt: '<p>You are writing a recursive-descent parser for the same grammar. You are inside the <code class="inline">expr()</code> function and have just consumed the first <code class="inline">term</code>. The next token is <code class="inline">+</code>. What does <code class="inline">expr()</code> do?</p>',
      mountInput: function (container) {
        var opts = [
          'Throw a syntax error — expr() is done as soon as it has a term.',
          'Consume the +, recursively call expr() again, and combine with the existing left.',
          'Consume the +, call term() to get the right side, then loop: build BinaryOp(+, left, right) and check for more + or -.',
          'Backtrack — return without consuming, let factor() handle the +.'
        ];
        var sel = document.createElement('select');
        opts.forEach(function (o, i) {
          var opt = document.createElement('option'); opt.value = String(i); opt.textContent = o;
          sel.appendChild(opt);
        });
        container.appendChild(sel);
        return function () { return sel.value; };
      },
      check: function (v) {
        if (v === '2') return { correct: true, feedback: 'Yes. The grammar has term followed by zero or more (+|-) term pieces, which becomes a while-loop in the parser. Each iteration pulls a fresh term and builds a left-associative tree.' };
        if (v === '1') return { correct: false, feedback: 'Calling expr() recursively here would make + RIGHT-associative (1+2+3 → 1+(2+3)). The standard pattern uses term() and a loop.' };
        if (v === '3') return { correct: false, feedback: 'The + is not part of factor()\'s grammar. Backtracking is also not how recursive descent normally works for this grammar.' };
        return { correct: false, feedback: 'Walk back through the grammar. expr ::= term (("+"|"-") term)* — the * means "loop in the parser".' };
      },
      hints: [
        'The * in the grammar maps to a while-loop in the parser, not recursion.',
        'Inside the loop: eat the operator, parse another term, build the BinaryOp.',
        'This loop pattern produces left-associativity (1+2+3 parses as ((1+2)+3)).'
      ]
    },
    {
      difficulty: 'hard',
      prompt: '<p>The "dangling else" problem: in the snippet</p>' +
              '<pre class="formula-box">if (a)\n    if (b)\n        X;\n    else\n        Y;</pre>' +
              '<p>...with no precedence rule, both <i>else-attaches-to-inner</i> and <i>else-attaches-to-outer</i> are valid parses. C, Java, JavaScript, and most others resolve this with the same fixed rule. <b>Which one?</b></p>',
      mountInput: function (container) {
        var opts = [
          'else attaches to the innermost unmatched if (here: "if (b)")',
          'else attaches to the outermost unmatched if (here: "if (a)")',
          'this is always a syntax error and must be parenthesized',
          'depends on indentation'
        ];
        var sel = document.createElement('select');
        opts.forEach(function (o, i) {
          var opt = document.createElement('option'); opt.value = String(i); opt.textContent = o;
          sel.appendChild(opt);
        });
        container.appendChild(sel);
        return function () { return sel.value; };
      },
      check: function (v) {
        if (v === '0') return { correct: true, feedback: 'Right. "Else binds to the nearest if" is the universal convention in C-family languages. Indentation in C-family languages is purely cosmetic — the parser ignores it.' };
        if (v === '3') return { correct: false, feedback: 'Indentation matters in Python and Haskell, but C-family languages parse purely from braces and the dangling-else rule. The snippet here is C-style.' };
        if (v === '2') return { correct: false, feedback: 'It is not a syntax error. The grammar accepts it; it just needs a tie-breaker.' };
        return { correct: false, feedback: 'Almost — but C/Java/JS pick the OTHER one of these two options. Think about what is closer.' };
      },
      hints: [
        'Languages either pick "innermost" or "outermost". One feels weirder to most people; that is the one chosen.',
        'Pascal famously goes with the same rule as C. The choice is universal in this family.',
        'Else binds to the NEAREST if. To attach else to the outer if, you have to add explicit braces around the inner if.'
      ]
    }
  ]
});
